
CXX = g++

CXXFLAGS = -std=c++11
CXXFLAGS += -Wall
CXXFLAGS += -g
 
SRC1 = main.cpp
SRC2 = Fib.cpp

SRCS = ${SRC1} ${SRC2} 

PROG1 = main
PROGS = ${PROG1}

all:
	$(CXX) $(CXXFLAGS) ${SRCS} -o ${PROG1} 

#--track-origins=yes

clean:
	rm *.o main 








